version: '3.1'

services:

  db:
    image: percona:5.7
    volumes:
      - db_data_v2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

volumes:
   db_data_v2:
